wip_test_product_reviews_smoke
jpmarcantonio/ecom-automation-pytest pull request #6
Opened 2024-02-16 12:36 UTC by jpmarcantonio

2024-02-17 16:37 UTC, admaskinfu requested changes
I think about 2 of the comments need to be addressed before approving so I am not approving yet. Just make those changes.

2024-02-17 16:37 UTC, admaskinfu commented on demostore_automation/src/generic_helpers/generic_products_helper.py
> +    def create_a_product(self):
Just an idea: theis function you can probably allow users to pass in the product name and type and may be few things. But make them optional. meaning you can give it default value of None and in the body you can check if it is None then generate random, if not None use what is passed. For the 'type' you can just give it default value of 'simple'. 
I say that so the function is flexible without adding much more work.
Example: `def create_a_product(self, product_name=None, type='simple')`

2024-02-17 16:37 UTC, admaskinfu commented on demostore_automation/src/utilities/genericUtilities.py
> +def generate_random_string(string_length=10):
Why is htis under the 'if __name__ == '__main__' block? It shouldn't be below that. It is not in that block so it works but the 'if' block should be at the end of the script. Technialy it shouldn't even be there. It was the 'if __name__' block was useful to just test the script by itself. So just delete it. No need to have that anymore.

2024-02-17 16:37 UTC, admaskinfu commented on demostore_automation/tests/backend/products/product_reviews/test_product_reviews_smoke.py
> +
you should add mark 'moke' on smoke tests. 
Because you want to set up a job that runs only smoke tests and no you don't have a way to run only smoke tests.

2024-02-17 16:37 UTC, admaskinfu commented on demostore_automation/tests/backend/products/product_reviews/test_product_reviews_smoke.py
> +            assert rs_review_api['product_id'] == product_id, f"Create feview response unexpected 'product_id'. Expected: {product_id}, Actual: {rs_review_api['product_id']}"
typo: "feview" meant to say "review"

2024-02-17 16:37 UTC, admaskinfu commented on demostore_automation/tests/backend/products/product_reviews/test_product_reviews_smoke.py
> +        rating_count_difference = qty_review_to_add - product_info_after['rating_count']
Well if you are calculating the number of reviews based on what is actually displayed then this will always be true.
It is not a real test then right? Not sure if I am thinking of it right or if I am explaining it right.
but you cant make your calculation based on the actual result and compare it to the actual result. 
You know the review is always off by 1 (that is the bug) so just subtract 1.

2024-02-17 16:37 UTC, admaskinfu commented on demostore_automation/tests/backend/products/product_reviews/test_product_reviews_smoke.py
> +        ## get all reviews for the given product
Either implement this or remove these comments.
If you want to keep them as reminders for the future then add # TODO:

In PyCharm, there is a tab at the bottom that says TODO, which will ist out all your todos.

2024-02-18 14:08 UTC, jpmarcantonio commented on demostore_automation/tests/backend/products/product_reviews/test_product_reviews_smoke.py
> +            rating = random.randint(1, 5)
User is unable to leave a 0 star review on website and rating count does not count 0 star reviews. Now the bug consistently shows 1 less than expected.

2024-02-19 14:24 UTC, super-sqa approved these changes
Great work.

2024-02-20 10:50 UTC, merged